import Head from 'next/head'
import Image from 'next/image'
import { FaFacebookF, FaTwitter, FaInstagram, FaLinkedinIn, FaYoutube } from "react-icons/fa";
import Nav from '@/components/Nav/Nav'
import Card from '@/components/Card/Card';
import Footer from '@/components/Footer/Footer';
import { useState } from 'react';
import Modal from '@/components/Modal.js/Modal';






export default function Home({ data }) {

  const popular = data.slice(0, 32)

  const [load, setLoad] = useState(8);

  function more() {
    if (load <= 32) {
      setLoad(load + 4)
    }
  }

  const [modal, setModal] = useState(false);

  const closeModal = () => { setModal(false) }


  const [search, setSearch] = useState("");


  return (
    <>
      <Head>
        <title>Exclusive Books</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Philosopher:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet"></link>
      </Head>

      <nav>
        <Nav setSearch={setSearch} search={search} />
      </nav>

      <main>


        {/* CAROUSEL .............................................. */}
        <div className='bg-[#f8f9fa] h-96'>
          <p>CAROUSEL</p>
        </div>


        {/* SECTION 1 .......................................... */}
        <div className='flex justify-center items-center gap-8 h-[350px] lg:gap-3 lg:ml-5 lg:mr-5 md:gap-3 md:ml-2 md:mr-2 '>

          <div className='flex shadow-lg rounded-lg '>
            <div className='overflow-hidden'>
              <div className='hover:scale-110 transition-all duration-500 cursor-pointer'>
                <Image className='rounded' src={"/book1.jpg"} width={330} height={220} />
              </div>
            </div>
            <div className='flex flex-col justify-center gap-4 w-[350px] pl-12 text-xl lg:text-lg lg:gap-2 lg:pl-8 lg:w-[300px] md:text-lg md:gap-2 md:pl-5'>
              <p className='text-green-600 font-bold'>Sale up to 15%</p>
              <p className='font-bold op'>Innovation in Education <br />(Hardcover)</p>
              <p>Starting at: <span className='text-green-600'>$65.09</span></p>
            </div>
          </div>

          <div className='flex shadow-lg rounded-lg'>

            <div className='overflow-hidden'>
              <div className='hover:scale-110 transition-all duration-500 cursor-pointer'>
                <Image className='rounded' src={"/book2.jpg"} width={330} height={220} />
              </div>
            </div>


            <div className='flex flex-col justify-center gap-4 w-[350px] pl-12 text-xl lg:text-lg lg:gap-2 lg:pl-8 lg:w-[300px] md:text-lg md:gap-2 md:pl-5'>
              <p className='text-green-600 font-bold'>Sale up to 10%</p>
              <p className='font-bold op'>Innovation in Education <br /> (Hardcover)</p>
              <p>Starting at: <span className='text-green-600'>$50.09</span></p>
            </div>
          </div>

        </div>

        {/* CARD ..................................................... */}
        <div className='bg-[#f8f9fa] flex flex-col items-center pb-10'>
          {/* titre .................*/}
          <div className='flex flex-col items-center pt-20 mb-20'>
            <p className=' text-green-600 font-bold tracking-widest'>BOOKS GALLERY</p>
            <p className='op font-semibold text-4xl pb-4'>Popular Books</p>
            <Image src={"/HR.png"} width={250} height={60} />
          </div>

          {/* card .......................*/}
          <div className='pl-40 pr-40 flex flex-wrap gap-10 justify-center pb-20'>
            {popular
              .filter(item => {
                return search === "" ? item :
                  item.title.toLowerCase().includes(search.toLowerCase())
              })
              .map((element, index) => {
                if (index < load) {
                  return (
                    <Card element={element} setModal={setModal} />
                  );
                }
              })}
          </div>




          {/* LOAD MORE................................ */}
          <div onClick={() => more()} class="relative inline-flex px-5 py-3 overflow-hidden group bg-[#5a8f7b] cursor-pointer">
            <span class="w-32 h-32 rotate-45 translate-x-12 -translate-y-2 absolute left-0 top-0"></span>
            <span class="absolute top-0 left-0 w-48 h-48 -mt-1 transition-all duration-500 ease-in-out rotate-45 -translate-x-56 -translate-y-24 bg-[#2f4858] opacity-100 group-hover:-translate-x-8"></span>
            <span class="relative w-full text-left text-white transition-colors duration-200 ease-in-out">Load More</span>
            <span class="absolute inset-0"></span>
          </div>
        </div>






        {/* JOIN .......................................... */}
        <div className='h-[450px] flex flex-col items-center justify-center'>

          <div className='border p-6 flex shadow-lg rounded-lg gap-5'>
            <div>
              <Image className='rounded-lg' src={"/bk-join.png"} width={415} height={225} />
            </div>

            <div className='flex flex-col gap-5'>
              <p className='op text-3xl font-semibold'>Join Our Community</p>
              <p>sign up & get 10% of first books</p>

              <div>
                <input className='border shadow-lg p-2 w-[400px] h-[50px]' type="text" placeholder='Your email' />
                <a href="#_" class="relative inline-flex px-5 py-3 overflow-hidden group bg-[#5a8f7b]">
                  <span class="w-32 h-32 rotate-45 translate-x-12 -translate-y-2 absolute left-0 top-0"></span>
                  <span class="absolute top-0 left-0 w-48 h-48 -mt-1 transition-all duration-500 ease-in-out rotate-45 -translate-x-56 -translate-y-24 bg-[#2f4858] opacity-100 group-hover:-translate-x-8"></span>
                  <span class="relative w-full text-left text-white transition-colors duration-200 ease-in-out">Subscribe</span>
                  <span class="absolute inset-0"></span>
                </a>
              </div>

              <div className='flex gap-3'>
                <FaFacebookF className='bg-[#5a8f7b] text-white rounded-full w-8 h-8 p-2 hover:bg-[#2f4858] transition duration-200 ease-out hover:ease-in' />
                <FaTwitter className='bg-[#5a8f7b] text-white rounded-full w-8 h-8 p-2 hover:bg-[#2f4858] transition duration-200 ease-out hover:ease-in' />
                <FaInstagram className='bg-[#5a8f7b] text-white rounded-full w-8 h-8 p-2 hover:bg-[#2f4858] transition duration-200 ease-out hover:ease-in' />
                <FaLinkedinIn className='bg-[#5a8f7b] text-white rounded-full w-8 h-8 p-2 hover:bg-[#2f4858] transition duration-200 ease-out hover:ease-in' />
                <FaYoutube className='bg-[#5a8f7b] text-white rounded-full w-8 h-8 p-2 hover:bg-[#2f4858] transition duration-200 ease-out hover:ease-in' />
              </div>
            </div>

          </div>

        </div>

        <Modal onClose={closeModal} visible={modal} />


      </main>

      <footer>
        <Footer />
      </footer>

    </>
  )
}



export async function getStaticProps() {
  const response = await fetch("https://example-data.draftbit.com/books")
  const data = await response.json()

  return {
    props: {
      data
    }
  }
}
